Feature/plugin installation from config
NeonGeckoCom/neon_speech pull request #190
Opened 2024-02-22 09:22 UTC by dblencowe

# Description

- Expand the entrypoint with an additional command, "install-dependencies" command
- Add utility function for building a dependency list from extra_dependencies and modules or fallbacks specified in TTS configuration
- Mark neon_audio.utils.install_tts_plugin as deprecated

# Issues
https://github.com/NeonGeckoCom/neon_enclosure/issues/84

# Other Notes

2024-02-22 18:37 UTC, NeonDaniel requested changes
Couple of small notes

2024-02-22 18:37 UTC, NeonDaniel commented on neon_speech/utils.py
> +    dependencies = additional + extra_dependencies.get("global", []) + extra_dependencies.get("neon-speech", [])
Refactor `neon-speech` to `voice` to match `ready_settings` spec

2024-02-22 18:37 UTC, NeonDaniel commented on requirements/requirements.txt
> +neon-utils[network]~=1.8,>=1.8.3a5
Replace `audio` extra dependency

2024-02-23 17:29 UTC, NeonDaniel approved these changes

2024-02-24 03:15 UTC, mikejgray reviewed
It doesn't look like the same bug is present here as in neon_audio, but if you have plans to try to infer a PyPi package to install from `stt.module`, make sure it has strong error handling so it doesn't fail to load if `stt.module` doesn't match a package on PyPi 🙂

2024-03-01 03:34 UTC, mikejgray approved these changes

2024-04-09 01:05 UTC, merged